mykso/myks

cmd/all.go, internal/myks/environment.go, internal/myks/globe.go, internal/myks/util.go
=> perf: process environments and applications in parallel

go.mod, go.sum, internal/myks/util.go, internal/myks/util_test.go
This commit adds support for asynchronous processing in the `process` function. It allows tasks to be executed concurrently based on the specified `asyncLevel`. Additionally, test cases have been added to ensure the correct execution of the function.
=> feat: Add async processing and tests

internal/myks/application.go, internal/myks/assets/data-schema.ytt.yaml, internal/myks/render_helm.go
Capabilities can be defined in env-data.ytt.yaml.
Capabilities are passed to helm template.
Fixes #31
=> feat(helm): add support for helm capabilities

internal/myks/environment.go
The behavior has been changed:
If everything is rendered, the errors are fatal if an app does not exist.
If apps are passed via command line, myks is a bit more relaxed.
The difficulty is that an app may exist for another application.
=> feat: fail on non existing apps

internal/myks/application.go, internal/myks/assets/data-schema.ytt.yaml, internal/myks/render_test.go, internal/myks/sync.go
- Changed `data-schema` comments to be more informative and less redundant.
- Moved sync cache config from the `application` scope within `data-schema` to its own `sync` scope.
- Renamed keys for simplicity (`cached` → `useCache`, `cache.enabled` → `useCache`).
=> refactor: vendir config

cmd/all.go, cmd/render.go, cmd/root.go, cmd/sync.go, go.mod, go.sum
fixes #82
There are two changes here:
- Usage of the `Command.Annotations` to identify supported commands.
- Using `args` as is (`cobra` takes care of stripping the subcommand from the arguments **before** passing them to the hook functions).
=> fix: apply smart mode logic only to supported commands

go.mod, go.sum, internal/myks/application.go, internal/myks/environment.go, internal/myks/globe.go, internal/myks/render.go, internal/myks/render_helm.go, internal/myks/sync.go, internal/myks/util.go
At least one occurrence of race conditions was observed: when running `myks sync` for a number of applications, generated `vendir.yaml` files get mixed up. The following lines of logs demonstrate the issue:
```
3:15PM DBG [phoenix-platform-production > httpbingo > sync] Running ytt to: creating vendir config
ytt --file=lib --file=.myks/tmp/data-schema.ytt.yaml --file=.myks/tmp/myks-data.ytt.yaml --file=prototypes/monitoring/vendir
```
Notice that this log output is printed for the `httpbingo` application, but the `ytt` command gets `--file=prototypes/monitoring/vendir` as one of the arguments.
This happens in this function: https://github.com/mykso/myks/blob/215ccd3f51231c20a07c92350eb7d0379dfd0784/internal/myks/util.go#L275-L287
~Somehow the `paths` value is changed outside. Sometimes it …
=> fix: reduce usage of pointers to cope with race conditions

SMARTMODE.md, internal/myks/sync.go, internal/myks/sync_test.go, internal/myks/util.go, internal/myks/util_test.go, testData/sync/sync-file.yaml, testData/sync/vendir-multiple-contents.yaml
Closes #81 
Apart from that, the code is simplified by throwing away Secrets and using path-to-hash map instead of an array of `Directory` items.
=> feat: support multiple content items in vendir configs

internal/myks/smart_mode.go, internal/myks/smart_mode_test.go
=> fix(smart-mode): Correct detection of changes in "_env/argocd"

internal/myks/render_global_ytt.go
I want to see the message, please use "#! for comments" directly :)
=> feat(global-ytt): log ytt output on error

internal/myks/sync.go
When a vendir directory contains a trailing slash, myks is not correctly cleaning up vendor directory.
Fixes #155
=> fix(sync): trim path separator from vendir directories

cmd/root.go, cmd/smart-mode.go, internal/myks/plugins.go
Small tweaks to the log output to get a clean log output. Please feast your eyes on my new "apply" plugin output driven by sops, kubeconform and kapp:
```
8:59AM INF [local-kind > my-workload > apply] Plugin execution succeeded:
Decrypting secrets
Validating Kubernetes manifests
Applying Kubernetes manifests
Target cluster 'https://127.0.0.1:45811' (nodes: dev-cluster-control-plane, 2+)
Changes
Namespace  Name  Kind  Age  Op  Op st.  Wait to  Rs  Ri  
Op:      0 create, 0 delete, 0 update, 0 noop, 0 exists
Wait to: 0 reconcile, 0 delete, 0 noop
Succeeded
Encrypting secrets
```
FYI: This is my apply script:
```
#! /usr/bin/env bash
function prepare() {
local action="$1"
local exit_code=0
if [[ -e "$MYKS_RENDERED_APP_DIR"/static ]]; then
case "$action" in
"encrypt")
echo "Encrypting …
```
=> fix(plugins): improve logging

internal/myks/smart_mode.go
=> fix(smart_mode): add static files directory

cmd/plugin.go, internal/myks/util.go
Small changes to the log output
=> chore: Log tweaks

cmd/init.go, go.sum, internal/myks/git.go, internal/myks/globe.go, internal/myks/smart_mode.go
- fix(init): do not discover git environment
- chore: go mod tidy
- refactor: move git functions out of Globe
- fix: handle no-git situation during init and in Smart Mode
Fixes #188
=> fix: decrease amount of git-related errors and warnings

examples/default/envs/mykso/dev/_apps/goldpinger/.myks/vendir.lock.yaml, examples/default/envs/mykso/dev/_apps/goldpinger/.myks/vendir.yaml, examples/default/envs/mykso/dev/env-data.ytt.yaml, examples/default/prototypes/goldpinger/vendir/base.yaml, examples/default/prototypes/goldpinger/vendir/vendir-data.ytt.yaml, examples/default/prototypes/goldpinger/ytt/grafana_dashboards.yaml, examples/default/readme.md, examples/default/rendered/argocd/mykso-dev/app-goldpinger.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/clusterrole-goldpinger-clusterrole.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/clusterrolebinding-goldpinger-clusterrolebinding.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/configmap-goldpinger-zap.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/daemonset-goldpinger.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/list-dashboard-configmap.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/service-goldpinger.yaml, examples/default/rendered/envs/mykso-dev/goldpinger/serviceaccount-goldpinger.yaml
This MR adds another example for a prototype `goldpinger`.
The prototype has two sources:
- helm chart
- ytt content (in this special case grafana dashboards as .json files)
This works nicely with myks `3.4.2` but not with #257 
So we should think if we want to support this use case.
The other option would be to create two prototypes (one for the helm chart, one for ytt)
=> test: add prototype with two vendir sources

internal/myks/globe.go
This fixes the issue when it is not possible to override values automatically set via `.myks/tmp/myks-data.ytt.yaml` with values set in e.g. `envs/env-data.ytt.yaml`, if `envs/env-data.ytt.yaml` is `data/values-schema`.
`data/values` files have higher precedence than `data/values-schema` files, so the values set in `data/values` files will override the values set in `data/values-schema` files.
=> fix: switch generated data values to schema to lower priority

internal/myks/assets/gitignore
This PR updates the `.gitignore` file that is created by the `myks init` command to reflect the latest changes in the `.myks` directory.
With these changes, the following files are ignored:
- `.myks/tmp`: data schema and values files managed by `myks` and refreshed on every run
- `.myks/envs/**/helm`: helm values files generated by `myks` on every render of this app
- `.myks/envs/**/steps`: yaml files with intermediate results of the rendering steps
- `.myks/envs/**/argocd_defaults.ytt.yaml`: generated on every run default data values for the ArgoCD plugin
What is not ignored by default (these files are useful for debugging and tracking upstream changes in PRs):
- `.myks/vendir-cache`: vendir cache entries
- this probably should be ignored by default, users can decide whether to carry the …
=> fix: adjust the initial .gitignore for the latest changes

examples/integration-tests/envs/dev/_apps/argocd-tests/app-data.ytt.yaml, examples/integration-tests/envs/dev/env-data.ytt.yaml, examples/integration-tests/rendered/argocd/mykso-dev/app-argocd-tests.yaml, examples/integration-tests/rendered/envs/mykso-dev/argocd-tests/rendering-base.yaml, examples/integration-tests/rendered/envs/mykso-dev/argocd-tests/rendering-proto.yaml, examples/simple/rendered/argocd/mykso-dev/app-httpbingo.yaml, internal/myks/templates/argocd/application.ytt.yaml
By default `argocd.app.source.plugin` is set to `null`.
This value is rendered literally in the ArgoCD Applicaion CR,
which causes the ArgoCD to fail to sync the application,
as ArgoCD expects an object here.
This PR changes the Application template to omit the field if it's empty.
=> fix: skip ArgoCD Application plugin if not set

internal/myks/application.go, internal/myks/environment.go, internal/myks/globe.go, internal/myks/smart_mode.go, internal/myks/smart_mode_test.go
Allowing multiple files per levels allows to split values into multiple files and/or define an own schema for environments.
This change is backward compatible: `env-data.ytt.yaml` and `app-data.ytt.yaml` are still working as before.
=> feat: allow multiple files for app and env-data on each level

internal/myks/assets/data-schema.ytt.yaml
This PR fixes an issue when the default values of boolean `helm.*` options are owerwritten by default values of the corresponding `helm.charts.*` options.
For example, with all default values, `includeCRDs` option becomes disabled, whereas it is expected to be enabled by default.
=> fix: make per-chart helm options nullable

internal/myks/assets/data-schema.ytt.yaml
In YTT an annotation affects either its left node or its right node, in this
exact order. To make sure the annotation is applied to the bottom node, we have
to ensure there's no node to the left of it.
In this case, the `releaseName` key is moved to the top of the list, to achieve
that.
=> fix: ensure buildDependencies is nullable

internal/myks/globe.go, internal/myks/globe_test.go, testData/collect-environments/envs/bar/prod/env-data.ytt.yaml, testData/collect-environments/envs/bar/stage/env-data.ytt.yaml, testData/collect-environments/envs/foo/prod/env-data.ytt.yaml, testData/collect-environments/envs/foo/stage/env-data.ytt.yaml
Before, if myks is tasked to process several intersecting environments, the
application list from the last collected environment was winning.
For example, with the following search paths:
```
envs/foo: app1, app2
envs/foo/bar: app3
```
The environment `envs/foo/bar` was processed with `app3` instead of `app1`,
`app2`, and `app3`.
Moreover, empty application lists were not handled correctly. If an application
list is empty, all applications in the environment should be processed.
=> fix: correctly assign apps to nested envs
